festive/ads/urls.py
from django.urls import path,include
from . import views
# from rest_framework import routers

# router = routers.DefaultRouter()
# router.register('record',views.recordList)

urlpatterns = [
    # path('route',include(router.urls)),
    path('',views.main, name='festive-circle'),
    path('add-venue',views.add, name='add'),
    path('search/q=ca_<category>&ct_<city>&min-pr_<min_price>&max-pr_<max_price>',views.search, name='search'),
    path('venue/<id>/',views.display,name='display'),
    path('edit/<id>/',views.edit,name='edit'),
    path('delete/<id>/',views.delete,name='delete'),

    # path('main/<id>/',views.delete,name='delete'),
    # path('record/json/',views.json,name='json'),


]

festive/festive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('', include('ads.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),

]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

festive/ads/models.py
from django.db import models
from PIL import Image as PILImage
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import get_user_model as user_model

from django.core.files.uploadedfile import InMemoryUploadedFile
from io import BytesIO,StringIO
# Create your models here.
User = user_model()

class Location(models.Model):

	city = models.CharField( max_length=100)
	area = models.CharField( max_length=100)
	street = models.CharField( max_length=100)
	latitude = models.CharField( max_length=100)
	longitude = models.CharField( max_length=100)

	class Meta:
		verbose_name = "Location"
		verbose_name_plural = "Locations"

	def __str__(self):
		return '%s, %s, %s' % (self.street, self.area, self.city)

	def get_absolute_url(self):
		return reverse("Location_detail", kwargs={"pk": self.pk})

class Detail(models.Model):

	hotel_rating_choices  = (
		('1','1'),
		('2','2'),
		('3','3'),
		('4','4'),
		('5','5'),
	)
	
	title = models.CharField(max_length=100)
	loction_id = models.ForeignKey(Location, verbose_name="Location", on_delete=models.CASCADE)
	phoneNo = models.CharField( max_length=20)
	postDate = models.DateTimeField(default=timezone.now)
	featured = models.BooleanField(default=False)
	description = models.TextField()
	rating = models.IntegerField(choices=hotel_rating_choices, default=3)
	views = models.IntegerField(default=0)

	class Meta:
		verbose_name = "Detail"
		verbose_name_plural = "Details"

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("Detail_detail", kwargs={"pk": self.pk})


def upload_location(instance, filename):
    return "%s/%s/%s/%s" % ('Ads',instance.detail_id.loction_id.city,instance.detail_id.title, filename)


class images(models.Model):

	title = models.CharField(max_length=100)
	detail_id = models.ForeignKey(Detail, verbose_name="Detail", on_delete=models.CASCADE)
	image = models.ImageField(upload_to=upload_location,
							null=True,
							blank=True,
							width_field="width_field",
							height_field="height_field",
							default='model/def.jfif'
							)

	height_field = models.IntegerField(default=800)
	width_field = models.IntegerField(default=700)
	class Meta:
		verbose_name = "Image"
		verbose_name_plural = "Images"

	def save(self, *args, **kwargs):
		if self.image:
			img = PILImage.open( BytesIO( self.image.read() ) )
			width, height = img.size
			if width > 700 or height > 800:
				width, height = 700, 800
			img.thumbnail( (width, height), PILImage.ANTIALIAS )
			save_buff = BytesIO()
			img2 = PILImage.open('media/cooltext333913402881516.png')
			img2.convert('RGBA')
			img.convert('RGBA')
			img.paste(img2, (0, 0), img2)

			img.save( save_buff,format='JPEG', optimize=True, quality=100)
			self.image = InMemoryUploadedFile( save_buff, 'ImageField', "%s" %self.title, 'image/jpeg',save_buff.__le__,  None )
		super( images, self ).save( *args, **kwargs )



class Venue(models.Model):

	STATUS_CHOICES = (
		("Banquet Hall", "Banquet Hall"),
		("Marquee", "Marquee"),
		("Hotel Hall", "Hotel Hall"),
		("Farmhouse", "Farmhouse"),
		("Lawn", "Lawn")
	)
	author =models.ForeignKey(User, on_delete=models.CASCADE)
	detail_id = models.ForeignKey(Detail, verbose_name="Detail", on_delete=models.CASCADE)
	sitting_capacity = models.IntegerField()
	category = models.CharField(choices=STATUS_CHOICES,max_length=50, default="Banquet Hall") 
	parking_capacity = models.IntegerField()
	air_conditioner = models.CharField( max_length=30,blank=True, null=True)
	heater = models.CharField( max_length=30,blank=True, null=True)
	dj_system = models.CharField( max_length=30,blank=True, null=True)
	wifi = models.CharField( max_length=30,blank=True, null=True)
	bridal_room = models.CharField( max_length=30,blank=True, null=True)
	valet_parking = models.CharField( max_length=30,blank=True, null=True)
	decoration = models.CharField( max_length=30,blank=True, null=True)
	generator = models.CharField( max_length=30,blank=True, null=True)
	outside_catering = models.CharField( max_length=30,blank=True, null=True)
	outside_dj = models.CharField( max_length=30,blank=True, null=True)
	outside_decoration = models.CharField( max_length=30)

	

	class Meta:
		verbose_name = "Venue"
		verbose_name_plural = "Venues"

	def get_absolute_url(self):
		return reverse("_detail", kwargs={"pk": self.pk})

class VenuePrice(models.Model):

	venue_id = models.ForeignKey(Venue, verbose_name="Venue", on_delete=models.CASCADE)
	per_guest = models.IntegerField()
	air_conditioner = models.IntegerField() 
	heater = models.IntegerField()
	dj_system = models.IntegerField()
	decoration = models.IntegerField()
	class Meta:
		verbose_name = "Venue Price"
		verbose_name_plural = "Venue Prices"
	def get_absolute_url(self):
		return reverse("VenuePrice_detail", kwargs={"pk": self.pk})

class Dish_Menu(models.Model):

	venue_id = models.ForeignKey(Venue, verbose_name="Venue", on_delete=models.CASCADE)
	title = models.CharField( max_length=100)
	description = models.TextField()
	price = models.IntegerField()

	class Meta:
		verbose_name = "Dish Menu"
		verbose_name_plural = "Dish Menus"

	def __str__(self):
		return str(self.price)

	def get_absolute_url(self):
		return reverse("Dish_Menu_detail", kwargs={"pk": self.pk})

festive/templates/base.html
</html>
<!doctype html>
<html lang="en">

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="/bower_components/bootstrap-horizon/bootstrap-horizon.css">

<!-- Fontawesome -->
<script src="https://kit.fontawesome.com/aab5290cf7.js" crossorigin="anonymous"></script>
<!-- JQuery -->
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
<title>Festive Circle</title>
{% block scripts %}
{% endblock %}
{% block style %}
<style>

</style>
{% endblock %}
</head>

<body>
  <!-- style="height: 100vh; background-image: linear-gradient(.25turn, #FBFCFC, 50%, #F2F4F4);" -->
  {% block main %}

  {% block top %}

  {% block nav %}

  <nav class="navbar navbar-expand-sm fixed-top" style="height: 50px; background:rgba(0,0,0,0.5);">
    <a class="navbar-brand" href="{% url 'festive-circle' %}">
      <img src="/media/icons/logo.png" class="img-fluid" style="width: auto; height: 40px;">
    </a>


    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown mr-4">
        <a class="btn btn-danger rounded-0" href="{% url 'add' %}">Post an Ad</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="" id="navbardrop" data-toggle="dropdown">
          <font size="2">Welcome {{user.name}}</font>
        </a>
        <div class="dropdown-menu">
          <a class="lead dropdown-item" href="{% url 'displayprofile' %}">
            <small>
              <font size="2">Display Profile</font>
            </small>
          </a>
          <a class="lead dropdown-item" href="{% url 'updateprofile' %}">
            <small>
              <font size="2">Update Profile</font>
            </small>
          </a>
          <a class="lead dropdown-item" href="{% url 'changepassword' %}">
            <small>
              <font size="2">Update Password</font>
            </small>
          </a>
          <div class="dropdown-divider"></div>
          <a class="lead dropdown-item" href="{% url 'logout' %}">
            <small>
              <font size="2">Logout</font>
            </small>
          </a>
        </div>
    </ul>
    {% else %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown mr-4">
          <a class="btn btn-danger rounded-0" href="{% url 'add' %}">Post an Ad</a>
      </li>
      <li class="nav-item active pt-1">
        <a class="nav-link bold text-white" href="{% url 'login' %}">
          <font size="2">Login</font>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link bold text-white" href="{% url 'register' %}">
          <font size="4">|</font>
        </a>
      </li>
      <li class="nav-item pt-1">
        <a class="nav-link bold text-white" href="{% url 'register' %}">
          <font size="2">Signup</font>
        </a>
      </li>
    </ul>
    {% endif %}
    <br>

  </nav>
  <br><br><br>
  {% endblock %}

  {% block alert %}

  {% if messages %}
  {% for message in messages %}
  {% if message.tags == 'password success' %}
  <div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>{{ message }}</strong>
  </div>
  {% endif %}
  {% if message.tags == 'message error' %}
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>{{ message }}</strong>
  </div>
  {% endif %}
  {% endfor %}
  {% else %}

  {% endif %}

  {% endblock %}

  {% endblock %}


  {% block mid %}

  {% endblock %}


  {% block end %}
  {% block footer %}
  <footer>
    <div class="container">

      <div class="row bg-dark justify-content-center pt-2">
        <div class="col-md-6 text-center">
          <h1 class="text-white p-2">
            Subscribe to our newsletter!
          </h1>
          <input type="email border" class="form-control" placeholder="example@mail.com">
          <h1 class="text-white p-2">
              Follow Us!
          </h1>
          <a class="text-white">
              <i class="fab fa-facebook p-1"></i>
              <i class="fab fa-twitter p-1"></i>
              <i class="fab fa-google p-1"></i>
              <i class="fab fa-youtube p-1"></i>
          </a>
          <h2 class="text-white p-2">
              <u>Download mobile apps!</u>
          </h2>
          <a class="text-white">
              <i class="fab fa-android p-1 fa-2x"></i>
              <i class="fab fa-apple p-1 fa-2x"></i>
          </a>
        </div>
      </div>
    </div>
  </footer>

  {% endblock %}

  {% endblock %}

  {% endblock %}

  {% block footscripts %}
  {% endblock %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

festive/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete</title>
</head>
<body style="padding: 40px;">
    <form action="" method="post">
        {% csrf_token %}
        <h2>Are you sure  you want to remove</h2>
        <button type="submit">Confirm</button>
    </form>
</body>
</html>

festive/templates/edit.html
{% extends 'base.html' %}
{% block main %}
{% block top %}



  {% block nav %}
  {{ block.super }}
  {% endblock nav %}
<script type="text/javascript" >
    $("#id_category").val("{{venues.category}}");
    
</script>
  <div class="container" style="padding: 3%">
        <div class="row">
            <div class="container">
                <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

        

                    <div class="container" style="background-color:rgb(255, 255, 255); margin-bottom: 50px">
                        <h2 style="padding: 3%">Add Information</h2>
                        <div class="col-md-10" style="padding-left: 20%;padding-bottom:10%">
                            <div class="form-group has-error">
                                <label for="title">Venue Title<span class="require">*</span></label>
                                <input type="text" class="form-control" name="post_title" value="{{ details.title }}"/>
                            </div>
                            <div class="form-group">
                                <label for="phone">Phone No <span class="require">*</span></label>
                                <input type="text" class="form-control" name="phone" value="{{details.phoneNo}}"/>
                            </div>
                            <div class="form-group">
                                <label for="location">City<span class="require">*</span></label>
                                <input type="text" class="form-control" name="city" value="{{details.loction_id.city}}"/>
                            </div>
                            <div class="form-group">
                                <label for="location">Area<span class="require">*</span></label>
                                <input type="text" class="form-control" name="area" value="{{details.loction_id.area}}"/>
                            </div>
                            <div class="form-group">
                                <label for="location">Sreet<span class="require">*</span></label>
                                <input type="text" class="form-control" name="street" value="{{details.loction_id.street}}"/>
                            </div>
                            <div class="form-group">
                                <label for="image">Images<span class="require">*</span></label>
                                <input type="file" class="form-control" id="images" name="images" value="{{images.image}}"
                                    onchange="preview_images();" multiple />
                            </div>
                            <div class="form-group" id="image_preview"></div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea rows="5" class="form-control" name="post_description" >{{details.description}}</textarea>
                            </div>
                        </div>
                    </div>

                    <div class="container" style="background-color:rgb(255, 255, 255); margin-bottom: 50px">
                        <h2 style="padding: 3%">Venue Price</h2>
                        <div class="col-md-10" style="padding-left: 20%;padding-bottom:10%">
                            <div class="form-group">
                                <label for="Price per guest">Per guest Price<span class="require">*</span></label>
                                <input type="text" class="form-control" name="guest_price" value="{{venuePrices.per_guest}}"/>
                            </div>
                            <div class="form-group">
                                <label for="Air condition">Air condition Price<span class="require">*</span></label>
                                <input type="text" class="form-control" name="ac_price" value="{{venuePrices.air_conditioner}}"/>
                            </div>
                            <div class="form-group">
                                <label for="title">Heater Price<span class="require">*</span></label>
                                <input type="text" class="form-control" name="heater_price" value="{{venuePrices.heater}}"/>
                            </div>
                            <div class="form-group">
                                <label for="title">DJ System Price<span class="require">*</span></label>
                                <input type="text" class="form-control" name="dj_system_price" value="{{venuePrices.dj_system}}"/>
                            </div>
                            <div class="form-group">
                                <label for="title">Decoration Price<span class="require">*</span></label>
                                <input type="text" class="form-control" name="decoration_price" value="{{venuePrices.decoration}}"/>
                            </div>
                        </div>
                    </div>

                    <div class="container" style="background-color:rgb(255, 255, 255); margin-bottom: 50px">
                        <h2 style="padding: 3%">Dish Menu</h2>
                        <div class="col-md-10" style="padding-left: 20%;padding-bottom:10%">
                            <div class="form-group">
                                <label for="title">Menu Title<span class="require">*</span></label>
                                <input type="text" class="form-control" name="dish_title" value="{{dishMenus.title}}"/>
                            </div>
                            <div class="form-group">
                                <label for="description">Menu Description<span class="require">*</span></label>
                                <input type="text" class="form-control" name="dish_description" value="{{dishMenus.description}}"/>
                            </div>
                            <div class="form-group">
                                <label for="price">Menu Price<span class="require">*</span></label>
                                <input type="text" class="form-control" name="price" value="{{dishMenus.price}}"/>
                            </div>
                        </div>
                    </div>

                    <div class="container" style="background-color:rgb(255, 255, 255); margin-bottom: 50px">
                        <h2 style="padding: 3%">Details</h2>
                        <div class="col-md-10" style="padding-left: 20%;padding-bottom:10%">
                            <div class="form-group">
                                <label for="Sitting Capacity">Sitting Capacity<span class="require">*</span></label>
                                <input type="text" class="form-control" name="sitting_capacity" value="{{venues.sitting_capacity}}"/>
                            </div>
                            <div class="form-group">
                                <label for="Parking Capacity">Parking Capacity<span class="require">*</span></label>
                                <input type="text" class="form-control" name="parking_capacity" value="{{venues.parking_capacity}}"/>
                            </div>
                            <div class="id_100">
                                <label class="required" for="id_category">Category</label>
                                
                                <select name="category" id="id_category" >
                                    <option value="Banquet Hall">Banquet Hall</option>

                                    <option value="Marquee">Marquee</option>

                                    <option value="Hotel Hall">Hotel Hall</option>

                                    <option value="Farmhouse">Farmhouse</option>

                                    <option value="Lawn">Lawn</option>

                                </select>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.decoration}}"
                                        name="decoration" >Decoration
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.wifi}}" name="wifi" >Wi-fi
                                </label>
                            </div>

                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.valet_parking}}"
                                        name="valet_parking" >valet parking
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.heater}}" name="heater">Heater
                                </label>
                            </div>
                            <div class="fom-check"></div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.air_conditioner}}" name="ac" >Air Condition
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.dj_system}}" name="dj_system" >DJ
                                    System
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.bridal_room}}"
                                        name="bridal_room" >Bridal Room
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.generator}}"
                                        name="generator" >Generator
                                </label>
                            </div>
                            <div class="fom-check"></div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.outside_dj}}"
                                        name="outside_dj" >Outside DJ
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.outside_decoration}}"
                                        name="outside_decoration" >Outside
                                    Decoration
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" value="{{venues.outside_catering}}"
                                        name="outside_catering" >Outside
                                    Catering
                                </label>
                            </div>
                        </div>
                    </div>
                    


                    <div class="form-group">
                            {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                            Add
                        </button>
                        <button class="btn btn-default">
                            Cancel
                        </button>
                    </div>

                </form>
            </div>

        </div>
    </div>
    {% endblock top %}
    {% block end %}
    {{ block.super }}
    
    {% endblock end %}
    {% endblock main %}

festive/templates/search.html
{% extends 'base.html' %}
{% block main %}
{% block top %}
  {% block nav %}
  {{ block.super }}
  {% endblock nav %}
SEARCH
<div class="container" style="margin: 10%">
 {% for key, value in det.items %}
    <div><a href="{% url 'display' value.id %}"> {{value}} </a></div>
 {% endfor %}
</div>
{% endblock top %}
{% block end %}
{{ block.super }}
{% endblock end %}
{% endblock main %}